### ISSUE TITLE
MQTT communication gets stuck via VPN connections

### ISSUE THREAD

**Issue by syssi** [homieiot/homie-esp8266#340] opened 2017-05-28 17:14 UTC
I've extended the TemperatureSensor example by 5 additional temperature HomieNodes. On boot the node gets stuck at the first publish of the configuration (the size of the message exceeds the MSS of 1336 bytes). My MQTT broker is located on another location accessible by OpenVPN. If I deploy a local MQTT broker the problem disappears (MSS 1460). If I reduce the length of the base topic, device id and property names the problem disappears also. I've attached screenshots of two tcpdumps. The long one is a proper connection to a local broker. The another one shows the node stuck after the MQTT "connect ack".

![mosquitto-local](https://cloud.githubusercontent.com/assets/2735933/26530678/ee71632c-43d9-11e7-8ac5-24b029beec41.png)

![mosquitto-remote](https://cloud.githubusercontent.com/assets/2735933/26530677/e9e85108-43d9-11e7-8ba6-0a85af6606ce.png)

After some time (keep alive timeout) the Node drops the MQTT connection and does a reconnect. The drop of the connection can be delayed by

```
Homie.getMqttClient().setKeepAlive(30);
Homie.setup();
```

A higher timeout does not solve the issue. The mosquitto.log shows the dropped connection as:

```
1495974899: New client connected from 192.168.130.53 as Homie-kitchen (c1, k15, u'username').
1495974920: Client Homie-kitchen has exceeded timeout, disconnecting.
```

**Comment by syssi** [comment] 2017-05-29 06:51
@me-no-dev do you have an idea whats happening here? It's a MSS problem and could it be ESPAsyncTCP related?

**Comment by marvinroger** [comment] 2017-05-30 18:00
Yes, the problem is in the underlying TCP lib. I cannot help here. 😕

**Comment by me-no-dev** [comment] 2017-05-30 18:23
AFAIK we have done everything possible to help with this. AsyncTCP reports everything that gets to it.

**Comment by marvinroger** [comment] 2017-05-30 18:27
Maybe the `esp8266/Arduino` 2.4.0 will help? I saw there's a WIP to port pure lwip 2.0, too.

**Comment by syssi** [comment] 2017-06-01 06:15
I will give it a try!

**Comment by marvinroger** [comment] 2017-06-01 20:41
Please also try with the latest AsyncMqttClient, it solved the timeout issue.

**Comment by syssi** [comment] 2017-06-03 15:21
I've updated a few libraries/components:

Arduino/libraries/homie-esp8266: master 65c7944cc21e5d48834565b19b4a0dd1b8581166
Arduino/libraries/async-mqtt-client: master 04a8332d965e083a572626cffeffd7308d5b7719
Arduino/libraries/ESPAsyncTCP: master 3d030db489e263e16a5af43a095c83c12ed8e451
Arduino/hardware/esp8266com/esp8266: master db8868da1d70517a28feefc1310b423d5710cba8

Unfortunately it does not fix the issue.

**Comment by Gulaschcowboy** [comment] 2017-09-03 16:42
Hi everybody,
please excuse me for jumping in here. I have the same problem with remote nodes behind ADSL lines here in Germany. Their MTU is 1492 bytes and sometimes even lower (seems to have some L2TP in between.
The initial package that contains ../$implementation doesn't get transferred over such line as the underlying packet is seems to be too big:
seq 104:1564, ack 5, win 5836, length 1460
This is reproducible, as I have a test bed where I can direct the packet over lines with MTU of 1500 which works and with lower MTUs it doesn't work

Following this thread I tested with esp-arduino 2.4.0-rc1, still same problem. :-(
As I'm not deep enough at all into the underlying libraries: Isn't there a way to manually patch the crafted packet size e.g. in ESPAsyncTCP @me-no-dev ?
Or is this a problem which can only be solved within  esp8266/Arduino? If yes, can somebody support me to file a bug to @iggr?

Thanks.

**Comment by timpur** [comment] 2017-09-05 23:25
Seem to be having the same problem with MTU's.

Trying to connect one device with loads of attributes to a remote mqtt server. When using my home network this doesnt work. It sends through one message and then fails, but when connected to my mobile hotspot works perfectly... NO vpn. any ideas on why this is? 

Home internet is using wireless broadband (4G)

**Comment by stritti** [comment] 2020-01-18 13:21
Closing this issue because of no progress for long time.

**Closed by stritti** 2020-01-18 13:21 UTC
Labels: 3rd party, bug

**Comment by stuz5000** [comment] 2020-03-13 05:43
Is this still an outstanding bug? I see it was closed but no sign it was fixed. (I'm having issues with keeping an connection over vpn).
