### ISSUE TITLE
$stats/interval always 0

### ISSUE THREAD

**Issue by mwildbolz** [homieiot/homie-esp8266#521] opened 2018-05-01 12:30 UTC
The topic $stats/interval is always 0.
Maybe because in L359 there is a division by 1000 where the value is already in seconds - for me there is no need to do this division.

https://github.com/marvinroger/homie-esp8266/blob/99161ce03c7ff1c8d3dc1fcc52abbf081212b68f/src/Homie/Boot/BootNormal.cpp#L359

**Comment by timpur** [comment] 2018-05-02 01:00
why is there no need for 'you' ? are you changing the $interval value from the default?

**Comment by mwildbolz** [comment] 2018-05-06 08:54
No need, because regarding to Homie specification this value is in seconds and the STATS_SEND_INTERVAL_SEC is also a value in seconds. So you don't need to divide it by 1000 - would only be necessary if the value is in ms.

And yes, I'm also changing the device_stats_interval through configuration.
I would also expect, that the changed value is written to this Homie topic.

**Comment by CapnBry** [comment] 2018-06-10 13:03
This report is correct, STATS_SEND_INTERVAL_SEC is in seconds and the code divides it by 1000 expecting it to be in milliseconds before outputting it. In the code:
```
  const uint32_t STATS_SEND_INTERVAL_SEC = 1 * 60;
```
Where it uses the interval it also expects seconds:
```
  _statsTimer.setInterval(Interface::get().getConfig().get().deviceStatsInterval * 1000);
```
So one of the two is wrong and I believe @mwildbolz is correct considering the constant name is SEC and not MSEC.

**Comment by timpur** [comment] 2018-06-11 08:16
Easy to fix, will do. Thanks guys

**Comment by stritti** [comment] 2019-04-04 12:21
@timpur could you confirm that it is corrected already?

**Comment by kleini** [comment] 2019-04-04 12:51
I can confirm, that $stat/interval is still zero for all of my devices using actual develop branch.

**Comment by tantive** [comment] 2019-04-26 17:42
If I remember corrected I fixed that one when I ported the lib to esp32 and made it play nicely with openHab (which requires repulishing interval in order to show a node as online).
So it should be fixed already in the develop-v3 branch.

**Comment by stritti** [comment] 2019-08-02 18:31
Works for me in combination of develop-V3 and openHab

**Closed by stritti** 2019-08-02 18:31 UTC
Labels: bug
